language: php
sudo: false

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: hhvm-nightly
        
branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

before_script:
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit
